# Generated by Django 4.1.3 on 2022-11-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_post_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
