# Generated by Django 4.1.3 on 2022-12-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_post_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
