# Generated by Django 4.1.3 on 2022-12-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_post_scrap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='slug1',
        ),
    ]
