# Generated by Django 4.1.3 on 2022-12-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
